# Generated by Django 3.2.5 on 2022-05-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name': '검색', 'verbose_name_plural': '검색'},
        ),
        migrations.AlterField(
            model_name='search',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='search',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
