# Generated by Django 3.2.13 on 2022-05-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_search_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='rating',
            field=models.CharField(default='', max_length=200),
        ),
    ]
