# Generated by Django 3.2.13 on 2022-05-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('scope', models.CharField(max_length=10, verbose_name='별점')),
                ('register_dttm', models.CharField(max_length=100, verbose_name='등록날짜')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰',
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='이미지 주소')),
            ],
            options={
                'verbose_name': '이미지',
                'verbose_name_plural': '이미지',
            },
        ),
        migrations.CreateModel(
            name='Kakao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(verbose_name='x')),
                ('y', models.FloatField(verbose_name='y')),
            ],
            options={
                'verbose_name': '위도-경도',
                'verbose_name_plural': '위도-경도',
            },
        ),
    ]
