# Generated by Django 3.2.5 on 2022-05-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='img',
            name='destination',
        ),
    ]
