# Generated by Django 3.2.5 on 2022-05-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='이미지 주소')),
            ],
            options={
                'verbose_name': '이미지',
                'verbose_name_plural': '이미지',
            },
        ),
    ]
